version: 0.2

phases:
  install:
    runtime-versions:
        python: 3.8
    commands:
        - pip install --upgrade awscli
  post_build:
    commands:
      - aws s3 sync ./src $S3_BUCKET --delete
